# Generated by Django 3.0.6 on 2020-06-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genre_genre_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['known_as']},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
